import React from 'react';
import { Printer, Download, ShieldCheck, FileCheck, Lock, AlertCircle, Building2, Calendar, FileText, ArrowLeft } from 'lucide-react';
import { CrimeCase } from '../../types';
import { redactSensitivePII } from '../../utils/entityExtractor';
import { formatHash } from '../../utils/cryptoUtils';

interface PoliceReportViewProps {
  currentCase: CrimeCase;
  piiRedacted: boolean;
  onBackToVault: () => void;
}

export const PoliceReportView: React.FC<PoliceReportViewProps> = ({
  currentCase,
  piiRedacted,
  onBackToVault,
}) => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 py-6 font-mono space-y-6">
      {/* Print / Export Action Bar */}
      <div className="bg-[#0F172A] border border-emerald-900/60 rounded-xl p-4 flex items-center justify-between shadow-xl print:hidden">
        <div className="flex items-center space-x-3">
          <button
            onClick={onBackToVault}
            className="flex items-center space-x-1 text-slate-400 hover:text-white text-xs bg-slate-800 px-3 py-1.5 rounded-lg border border-slate-700"
          >
            <ArrowLeft className="w-4 h-4" />
            <span>BACK TO VAULT</span>
          </button>
          <div>
            <h2 className="text-sm font-bold text-white flex items-center gap-2">
              POLICE-READY FORMAL COMPLAINT DOSSIER
              <span className="bg-emerald-950 text-emerald-300 border border-emerald-800 text-[10px] px-2 py-0.5 rounded font-mono">
                LAW ENFORCEMENT COMPLIANT
              </span>
            </h2>
            <p className="text-xs text-slate-400">SHA-256 verified digital evidence dossier formatted for Cyber Crime Units & Authorities</p>
          </div>
        </div>

        <div className="flex items-center space-x-3">
          <button
            onClick={handlePrint}
            className="flex items-center space-x-2 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-white font-mono text-xs font-bold px-4 py-2 rounded-lg shadow-lg shadow-emerald-500/20 border border-emerald-400/30 transition-all active:scale-95"
          >
            <Printer className="w-4 h-4" />
            <span>PRINT / SAVE AS PDF</span>
          </button>
        </div>
      </div>

      {/* Official Police Dossier Document Body */}
      <div className="bg-slate-950 text-slate-900 bg-white border border-slate-300 rounded-xl p-8 sm:p-12 shadow-2xl space-y-8 print:p-0 print:border-none print:shadow-none font-serif text-slate-900">
        
        {/* Official Header */}
        <div className="border-b-2 border-slate-900 pb-6 flex items-start justify-between">
          <div className="space-y-1">
            <div className="flex items-center space-x-2">
              <Building2 className="w-7 h-7 text-slate-800" />
              <h1 className="text-xl font-bold font-sans uppercase tracking-tight text-slate-900">
                CYBER CRIME INVESTIGATION REPORT
              </h1>
            </div>
            <p className="text-xs font-mono text-slate-700">Official Formal Complaint & Cryptographic Evidence Dossier</p>
            <p className="text-xs font-mono text-slate-600">Generated by AI Digital Crime Scene Investigator Platform</p>
          </div>

          <div className="text-right font-mono text-xs space-y-1">
            <div className="font-bold text-slate-900 bg-slate-100 p-2 rounded border border-slate-300">
              CASE REF: {currentCase.caseNumber}
            </div>
            <div className="text-slate-600">DATE: {new Date().toISOString().slice(0, 10)}</div>
            <div className="text-emerald-700 font-bold">STATUS: OFFICIAL EVIDENTIARY VAULT</div>
          </div>
        </div>

        {/* Executive Incident Summary */}
        <div className="space-y-3 font-sans">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-800 border-b border-slate-300 pb-1">
            1. Executive Incident Summary
          </h2>
          <div className="grid grid-cols-2 gap-4 text-xs font-mono bg-slate-50 p-4 rounded border border-slate-200">
            <div><strong>Scam Classification:</strong> {currentCase.scamCategory}</div>
            <div><strong>Total Financial Loss:</strong> ${currentCase.totalLossUSD.toLocaleString()} USD</div>
            <div><strong>Incident Period:</strong> {currentCase.incidentDate}</div>
            <div><strong>Evidence Exhibits Ingested:</strong> {currentCase.evidenceItems.length} Verified Files</div>
          </div>
          <p className="text-xs text-slate-800 leading-relaxed font-sans bg-slate-50 p-4 rounded border border-slate-200">
            {redactSensitivePII(currentCase.summary, piiRedacted)}
          </p>
        </div>

        {/* Victim & Suspect Profiles */}
        <div className="space-y-3 font-sans">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-800 border-b border-slate-300 pb-1">
            2. Parties & Identified Suspect Dossier
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
            {/* Victim Box */}
            <div className="bg-slate-50 p-4 rounded border border-slate-200 space-y-1.5 font-mono">
              <span className="font-bold text-slate-900 block border-b pb-1">VICTIM INFORMATION</span>
              <div><strong>Name:</strong> {redactSensitivePII(currentCase.victimName, piiRedacted)}</div>
              <div><strong>Contact:</strong> {redactSensitivePII(currentCase.victimContact, piiRedacted)}</div>
              <div><strong>Jurisdiction Location:</strong> {redactSensitivePII(currentCase.victimLocation, piiRedacted)}</div>
            </div>

            {/* Suspect Box */}
            <div className="bg-slate-50 p-4 rounded border border-slate-200 space-y-2 font-mono">
              <span className="font-bold text-red-700 block border-b pb-1">IDENTIFIED SUSPECT ALIASES</span>
              {currentCase.suspects.map((s, idx) => (
                <div key={idx} className="space-y-0.5 text-[11px]">
                  <div className="font-bold text-slate-900">{s.nameAlias} ({s.role})</div>
                  <div>Handle: <span className="text-cyan-800 font-bold">{s.handle}</span> | Phone: {s.phone}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Master Evidence Exhibit Index Table with SHA-256 Hashes */}
        <div className="space-y-3 font-sans">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-800 border-b border-slate-300 pb-1 flex justify-between items-center">
            <span>3. Cryptographic Master Evidence Exhibit Index</span>
            <span className="text-xs font-mono text-emerald-700 font-bold">Chain of Custody 100% Validated</span>
          </h2>

          <div className="overflow-x-auto border border-slate-300 rounded">
            <table className="w-full text-left text-xs font-mono">
              <thead className="bg-slate-100 border-b border-slate-300 text-slate-700">
                <tr>
                  <th className="p-2.5">Exhibit #</th>
                  <th className="p-2.5">Timestamp</th>
                  <th className="p-2.5">Source / Type</th>
                  <th className="p-2.5">Exhibit Title</th>
                  <th className="p-2.5">SHA-256 Hash Verification</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                {currentCase.evidenceItems.map(item => (
                  <tr key={item.id} className="hover:bg-slate-50">
                    <td className="p-2.5 font-bold text-cyan-900">{item.exhibitNumber}</td>
                    <td className="p-2.5 text-slate-700 whitespace-nowrap">{item.timestamp}</td>
                    <td className="p-2.5 uppercase text-slate-600 font-bold">{item.type}</td>
                    <td className="p-2.5 font-bold text-slate-900">{item.title}</td>
                    <td className="p-2.5 text-[10px] text-slate-600 font-mono break-all max-w-xs">{item.sha256Hash}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Recommended Law Enforcement Directives */}
        <div className="space-y-3 font-sans">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-800 border-b border-slate-300 pb-1">
            4. Recommended Law Enforcement Directives & Asset Freeze Demands
          </h2>
          <div className="space-y-2 text-xs font-mono">
            {currentCase.recommendedActions.map((action, i) => (
              <div key={i} className="bg-slate-50 border border-slate-200 p-3 rounded flex items-start gap-2 text-slate-900">
                <span className="font-bold text-slate-700">{i + 1}.</span>
                <span className="leading-relaxed">{action}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Official Signature & Verification Footer */}
        <div className="border-t-2 border-slate-900 pt-6 flex flex-col sm:flex-row items-center justify-between text-xs font-mono text-slate-600 gap-4">
          <div>
            <div>Investigator Certification & Cryptographic Lock</div>
            <div className="font-bold text-slate-900 mt-1">AI Crime Scene Investigator Vault Engine</div>
          </div>

          <div className="text-right space-y-1">
            <div className="border-b border-slate-400 w-48 ml-auto pb-1 text-center font-bold text-slate-800">
              Verified Digital Signature
            </div>
            <div className="text-[10px] text-slate-500">Document ID: {currentCase.id}-POLICE-READY</div>
          </div>
        </div>
      </div>
    </div>
  );
};
